# Generated by Django 4.1.11 on 2023-09-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_code', models.CharField(blank=True, max_length=100, null=True)),
                ('taxocode', models.TextField(blank=True, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('english_name', models.CharField(blank=True, max_length=100, null=True)),
                ('french_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spanish_name', models.CharField(blank=True, max_length=100, null=True)),
                ('arabic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chinese_name', models.CharField(blank=True, max_length=100, null=True)),
                ('russian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.CharField(blank=True, db_column='order_field', max_length=100, null=True)),
                ('stats_data', models.CharField(blank=True, max_length=100, null=True)),
                ('isscaap_code', models.FloatField(blank=True, null=True)),
                ('isscaap_group_en', models.CharField(blank=True, max_length=100, null=True)),
                ('isscaap_group_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('isscaap_group_es', models.CharField(blank=True, max_length=100, null=True)),
                ('isscaap_division_code', models.FloatField(blank=True, null=True)),
                ('isscaap_division_en', models.CharField(blank=True, max_length=100, null=True)),
                ('isscaap_division_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('isscaap_division_es', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fish',
            },
        ),
    ]
