# Generated by Django 4.1.11 on 2023-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='cleaned_file',
            field=models.FileField(blank=True, null=True, upload_to='cleaned_csv/'),
        ),
    ]
