# Generated by Django 4.1.11 on 2023-09-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_csvimport_cleaned_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='species_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
